# Generated by Django 5.2 on 2025-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes_Frecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField()),
                ('total_compras', models.IntegerField()),
                ('productos_mas_comprados', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Anual', 'Anual')], max_length=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_transacciones', models.IntegerField()),
                ('metodo_de_pago', models.JSONField(default=dict)),
                ('productos_mas_vendidos', models.JSONField(default=list)),
                ('fecha_creacion_reporte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stoks_Critico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral', models.IntegerField()),
                ('productos_bajo_stock', models.JSONField(default=list)),
                ('fecha_creacion_reporte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
