# Generated by Django 5.1.7 on 2025-05-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_compras', models.IntegerField()),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente Frecuente',
                'verbose_name_plural': 'Clientes Frecuentes',
                'ordering': ['-total_compras', 'cliente__username'],
            },
        ),
        migrations.CreateModel(
            name='StockCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField()),
                ('umbral', models.IntegerField(default=10)),
                ('fecha_creacion_reporte', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de Stock Crítico',
                'verbose_name_plural': 'Reportes de Stock Crítico',
                'ordering': ['-fecha_creacion_reporte', 'producto__nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Clientes_Frecuente',
        ),
        migrations.DeleteModel(
            name='Stoks_Critico',
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion_reporte'], 'verbose_name': 'Reporte de Ventas', 'verbose_name_plural': 'Reportes de Ventas'},
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='metodo_de_pago',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='productos_comprados',
        ),
    ]
