# Generated by Django 5.1.7 on 2025-05-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('Reportes', '0002_clientefrecuente_stockcritico_and_more'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientefrecuente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_cliente_frecuente', to='Usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='clientefrecuente',
            name='productos_mas_comprados',
            field=models.ManyToManyField(related_name='reportes_producto_frecuente', to='Productos.producto'),
        ),
        migrations.AddField(
            model_name='stockcritico',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_stock_critico', to='Productos.producto'),
        ),
    ]
