# Generated by Django 5.2 on 2025-05-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('Reportes', '0003_clientefrecuente_cliente_and_more'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientefrecuente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockcritico',
            options={},
        ),
        migrations.RemoveField(
            model_name='clientefrecuente',
            name='fecha_calculo',
        ),
        migrations.RemoveField(
            model_name='stockcritico',
            name='stock_actual',
        ),
        migrations.AddField(
            model_name='reporte',
            name='metodo_de_pago',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reporte',
            name='productos_comprados',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='clientefrecuente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='clientefrecuente',
            name='productos_mas_comprados',
            field=models.ManyToManyField(to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='stockcritico',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
    ]
