# Generated by Django 5.1.3 on 2025-05-23 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='Productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoComparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_producto1', to='Productos.producto')),
                ('producto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparaciones_producto2', to='Productos.producto')),
            ],
            options={
                'unique_together': {('producto1', 'producto2')},
            },
        ),
    ]
