# Generated by Django 5.1.3 on 2025-05-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_resena_productocomparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
