# Generated by Django 5.1.3 on 2025-05-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ranking',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
