# Generated by Django 5.2.1 on 2025-05-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_producto_imagen'),
    ]

    operations = [
    ]
